### ISSUE TITLE
Not working? Let me help you! :)

### ISSUE THREAD

**Issue by snkfranco** [4ksr/One-Armed-Robber#1]
If your program does not crash but it is not working either...
Just change this line of the code to this updated pointer:
`private readonly string ammoAddress = "OAR-Win64-Shipping.exe+04C233F0,1F0,108,50,260,8,20,2BC";`
this can help you.. :)
If i helped you, consider following meee ♥

**Comment by 4ksr** [comment]
its a old project and tk i will make it <3
